### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by losh11** [DoubleSha/BitcoinSwift#17]
Can someone post some usage documents for this project?
Or even a playground?

**Comment by kgreenek** [comment]
Apologies! I've been meaning to write up a getting started guide forever,
but just haven't gotten around to it. I definitely will once the library is
more complete.

In the scripts directory, dlheaders.swift is a swift script that will
connect to a bitcoin node running on localhost, and download all the
headers.

Right now, you can get a good idea of what is possible with the library by
looking at the PeerConnection class. It connects to a peer, exchanges
version information, and then starts calling its delegate whenever a new
message is received. The PeerController right now is currently just a demo
of sync'ing headers, but it will eventually do the SPV protocol with the
peer.

The library also supports a few other bits and pieces too. For example, HD
keys and secure key store are implemented and fully tested, the blockstore
works with CoreData, etc. Just poke around, and feel free to start building
out the missing bits if you want to get involved.
